name: mediaplayer-app
version: 0.20.5-1
summary: QML-based media player
description: |
  A QML media player that can play audio/video sources.
  Please find the source at:
  https://code.launchpad.net/mediaplayer-app
confinement: strict
grade: devel

apps:
  mediaplayer-app:
    command: desktop-launch $SNAP/bin/mediaplayer-app --desktop_file_hint=unity8 $@
    plugs: [mpris, opengl, platform, unity7, home]

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  mediaplayer-app:
    plugin: cmake
    source: .

    build-packages:
      - build-essential
      - debhelper
      - dh-translations
      - libgl1-mesa-dev
      - pkg-config
      - python3
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev

    configflags:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_LIBRARY_PATH=/usr/lib

    stage-packages:
      - xdg-user-dirs

    filesets:
      unwanted:
        # Files that we don't want/need in the final snap package
        - -etc
        - -usr/lib/debug
        - -usr/lib/*/libclick*
        - -usr/lib/*/libhybris*
        - -usr/lib/*/libogg*
        - -usr/lib/*/libpulse*
        - -usr/lib/python*
        - -usr/share/apport
        - -usr/share/bug
        - -usr/share/doc
        - -usr/share/fonts
        - -usr/share/libwacom
        - -usr/share/lintian
        - -usr/share/man
        - -usr/share/X11
        - -usr/lib/*.a
        - -usr/lib/*/*.a
        - -usr/lib/*.la
        - -usr/lib/*/*.la
        - -usr/lib/*/*.o

    snap:
      - $unwanted

    after:
      - desktop-ubuntu-app-platform

  environment:
    plugin: dump
    source: snap/
    organize:
      mediaplayer-app.wrapper: bin/mediaplayer-app
