name: mediaplayer-app
version: 0.20.5+17.04.20170321.4-0ubuntu1
summary: QML-based media player
description: |
  A QML media player that can play audio/video sources.
  Please find the source at:
  https://code.launchpad.net/mediaplayer-app
confinement: devmode
grade: stable

apps:
  mediaplayer-app:
    command: desktop-launch $SNAP/bin/mediaplayer-app --desktop_file_hint=unity8 $@
    plugs: [mpris, opengl, platform, unity7, home, unity8, mir-libs]

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

  mir-libs:
    interface: content
    content: mir0
    target: mir-libs
    default-provider: mir-libs

parts:
  mediaplayer-app:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_LIBRARY_PATH=/usr/lib]
    build-attributes: [no-system-libraries]
    source: .

    build-packages:
      - build-essential
      - debhelper
      - dh-translations
      - libgl1-mesa-dev
      - pkg-config
      - python3
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev

    stage-packages:
      - xdg-user-dirs
      - gstreamer1.0-libav

    after:
      - desktop-ubuntu-app-platform

  environment:
    plugin: dump
    source: snap/
    organize:
      mediaplayer-app.wrapper: bin/mediaplayer-app
